version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: Library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"  
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

